---

- name: Install Nginx Web Server on RedHat Family
  yum: name=nginx state=latest
  when:
    ansible_os_family == "RedHat"

- name: Install Nginx Web Server on Debian Family
  apt: name=nginx state=latest
  when:
    ansible_os_family == "Debian"

- name: Create home directory for www
  file:
    path: /var/www/{{ virtual_domain }}
    state: directory

- name: Remove default vh
  file:
    path: /etc/nginx/site-enabled/default
    state: absent

- name: Add virtual domain in NGINX for Deb
  vars:
    fastcgi_pass_path: /run/php/php7.4-fpm.sock
  template:
    src=templates/nginx_vhosts.conf
    dest=/etc/nginx/sites-enabled/{{ virtual_domain }}.conf
  when:
    ansible_os_family == "Debian"
  notify:
    - nginx start
